coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "benchmark"
  # All 'pb.go's.
  - "**/*.pb.go"
  # Tests and test related files.
  - "**/test"
  - "**/testutils"
  - "testdata"
  - "interop"
  # Other submodules.
  - "cmd"
  - "security"
  - "examples"
  - "gcp"
  - "stats/opensensus"
comment:
  layout: "header, diff, files"
