coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "benchmark/**/*"
  - "stress/**/*"
  # All 'pb.go's
  - "**/*.pb.go"
  # Tests and test related files.
  - "test/**/*"
  - "xds/internal/testutils/**/*"
  - "xds/internal/test/**/*"
  - "balancer/rls/internal/test/e2e/**/*"
  - "testdata"
  # Other submodules.
  - "security/**/*"
  - "examples/**/*"
  - "interop/**/*"
  - "stats/**/*"
  - "gcp/**/*"
comment:
  layout: "header, diff, files"
