version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_include:
          regex: '^Type:'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'All PRs must include an appropriate "Type:" label'
          summary: 'All PRs must include an appropriate "Type:" label'
  - when: pull_request.*
    validate:
      - do: label
        must_include:
          regex: '^no release notes$'
      - do: milestone
        must_include:
          regex: 'Release$'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'All PRs must include a Release milestone or the "no release notes" label'
          summary: 'All PRs must include a Release milestone or the "no release notes" label'
