version: 2
mergeable:
  - when: pull_request.*
    # This validator requires either the "no release notes" label OR the
    # "RELNOTES.md" file to be considered successful.  However, validators
    # "pass" in mergeable only if all checks pass.  So it is implemented in
    # reverse.
    #
    # I.e.: !(!no_relnotes && !release_milestone) ==> no_relnotes || release_milestone
    #
    # If both validators pass, then it is considered a failure, and if either
    # fails, it is considered a success.
    validate:
      - do: label
        must_exclude:
          regex: '^no release notes$'
      - do: changeset
        must_exclude:
          regex: '^RELNOTES.md$'
    pass:
      - do: checks
        status: 'failure'  # fail on pass
        payload:
          title: 'Need RELNOTES.md or "no release notes" label'
          summary: 'Need RELNOTES.md or "no release notes" label'
      - do: assign
        assignees: [ '@author' ]
    fail:
      - do: checks
        status: 'success' # pass on fail
