version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_include:
          regex: '^Type:'
      - do: description
        must_include:
          regex: 'RELEASE NOTES:'
      - do: milestone
        must_include:
          regex: 'Release$'
