version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_include:
          regex: '^Type:'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'Need an appropriate "Type:" label'
          summary: 'Need an appropriate "Type:" label'
  - when: pull_request.*
    validate:
      - do: label
        must_exclude:
          regex: '^no release notes$'
      - do: milestone
        must_exclude:
          regex: 'Release$'
    pass:
      - do: checks
        status: 'failure'
        payload:
          title: 'Need Release milestone or "no release notes" label'
          summary: 'Need Release milestone or "no release notes" label'
    fail:
      - do: checks
        status: 'success'
