version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_include:
          regex: '^no release notes$'
      - do: changeset
        must_exclude:
          regex: '^RELNOTES.md$'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'Need RELNOTES.md or "no release notes" label'
          summary: 'Need RELNOTES.md or "no release notes" label'
      - do: assign
        assignees: [ '@author' ]

  - when: pull_request.*
    validate:
      - do: label
        must_exclude:
          regex: '^no release notes$'
      - do: changeset
        must_include:
          regex: '^RELNOTES.md$'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'Need RELNOTES.md or "no release notes" label'
          summary: 'Need RELNOTES.md or "no release notes" label'
      - do: assign
        assignees: [ '@author' ]
