// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v2/endpoint/load_report.proto

package envoy_api_v2_endpoint

import (
	fmt "fmt"
	core "google.golang.org/grpc/xds/internal/proto/envoy/api/v2/core"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpstreamLocalityStats struct {
	Locality                *core.Locality             `protobuf:"bytes,1,opt,name=locality,proto3" json:"locality,omitempty"`
	TotalSuccessfulRequests uint64                     `protobuf:"varint,2,opt,name=total_successful_requests,json=totalSuccessfulRequests,proto3" json:"total_successful_requests,omitempty"`
	TotalRequestsInProgress uint64                     `protobuf:"varint,3,opt,name=total_requests_in_progress,json=totalRequestsInProgress,proto3" json:"total_requests_in_progress,omitempty"`
	TotalErrorRequests      uint64                     `protobuf:"varint,4,opt,name=total_error_requests,json=totalErrorRequests,proto3" json:"total_error_requests,omitempty"`
	TotalIssuedRequests     uint64                     `protobuf:"varint,8,opt,name=total_issued_requests,json=totalIssuedRequests,proto3" json:"total_issued_requests,omitempty"`
	LoadMetricStats         []*EndpointLoadMetricStats `protobuf:"bytes,5,rep,name=load_metric_stats,json=loadMetricStats,proto3" json:"load_metric_stats,omitempty"`
	UpstreamEndpointStats   []*UpstreamEndpointStats   `protobuf:"bytes,7,rep,name=upstream_endpoint_stats,json=upstreamEndpointStats,proto3" json:"upstream_endpoint_stats,omitempty"`
	Priority                uint32                     `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                   `json:"-"`
	XXX_unrecognized        []byte                     `json:"-"`
	XXX_sizecache           int32                      `json:"-"`
}

func (m *UpstreamLocalityStats) Reset()         { *m = UpstreamLocalityStats{} }
func (m *UpstreamLocalityStats) String() string { return proto.CompactTextString(m) }
func (*UpstreamLocalityStats) ProtoMessage()    {}
func (*UpstreamLocalityStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_5134f8f33d8f8d01, []int{0}
}

func (m *UpstreamLocalityStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamLocalityStats.Unmarshal(m, b)
}
func (m *UpstreamLocalityStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamLocalityStats.Marshal(b, m, deterministic)
}
func (m *UpstreamLocalityStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamLocalityStats.Merge(m, src)
}
func (m *UpstreamLocalityStats) XXX_Size() int {
	return xxx_messageInfo_UpstreamLocalityStats.Size(m)
}
func (m *UpstreamLocalityStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamLocalityStats.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamLocalityStats proto.InternalMessageInfo

func (m *UpstreamLocalityStats) GetLocality() *core.Locality {
	if m != nil {
		return m.Locality
	}
	return nil
}

func (m *UpstreamLocalityStats) GetTotalSuccessfulRequests() uint64 {
	if m != nil {
		return m.TotalSuccessfulRequests
	}
	return 0
}

func (m *UpstreamLocalityStats) GetTotalRequestsInProgress() uint64 {
	if m != nil {
		return m.TotalRequestsInProgress
	}
	return 0
}

func (m *UpstreamLocalityStats) GetTotalErrorRequests() uint64 {
	if m != nil {
		return m.TotalErrorRequests
	}
	return 0
}

func (m *UpstreamLocalityStats) GetTotalIssuedRequests() uint64 {
	if m != nil {
		return m.TotalIssuedRequests
	}
	return 0
}

func (m *UpstreamLocalityStats) GetLoadMetricStats() []*EndpointLoadMetricStats {
	if m != nil {
		return m.LoadMetricStats
	}
	return nil
}

func (m *UpstreamLocalityStats) GetUpstreamEndpointStats() []*UpstreamEndpointStats {
	if m != nil {
		return m.UpstreamEndpointStats
	}
	return nil
}

func (m *UpstreamLocalityStats) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type UpstreamEndpointStats struct {
	Address                 *core.Address              `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Metadata                *_struct.Struct            `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TotalSuccessfulRequests uint64                     `protobuf:"varint,2,opt,name=total_successful_requests,json=totalSuccessfulRequests,proto3" json:"total_successful_requests,omitempty"`
	TotalRequestsInProgress uint64                     `protobuf:"varint,3,opt,name=total_requests_in_progress,json=totalRequestsInProgress,proto3" json:"total_requests_in_progress,omitempty"`
	TotalErrorRequests      uint64                     `protobuf:"varint,4,opt,name=total_error_requests,json=totalErrorRequests,proto3" json:"total_error_requests,omitempty"`
	TotalIssuedRequests     uint64                     `protobuf:"varint,7,opt,name=total_issued_requests,json=totalIssuedRequests,proto3" json:"total_issued_requests,omitempty"`
	LoadMetricStats         []*EndpointLoadMetricStats `protobuf:"bytes,5,rep,name=load_metric_stats,json=loadMetricStats,proto3" json:"load_metric_stats,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                   `json:"-"`
	XXX_unrecognized        []byte                     `json:"-"`
	XXX_sizecache           int32                      `json:"-"`
}

func (m *UpstreamEndpointStats) Reset()         { *m = UpstreamEndpointStats{} }
func (m *UpstreamEndpointStats) String() string { return proto.CompactTextString(m) }
func (*UpstreamEndpointStats) ProtoMessage()    {}
func (*UpstreamEndpointStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_5134f8f33d8f8d01, []int{1}
}

func (m *UpstreamEndpointStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamEndpointStats.Unmarshal(m, b)
}
func (m *UpstreamEndpointStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamEndpointStats.Marshal(b, m, deterministic)
}
func (m *UpstreamEndpointStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamEndpointStats.Merge(m, src)
}
func (m *UpstreamEndpointStats) XXX_Size() int {
	return xxx_messageInfo_UpstreamEndpointStats.Size(m)
}
func (m *UpstreamEndpointStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamEndpointStats.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamEndpointStats proto.InternalMessageInfo

func (m *UpstreamEndpointStats) GetAddress() *core.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UpstreamEndpointStats) GetMetadata() *_struct.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *UpstreamEndpointStats) GetTotalSuccessfulRequests() uint64 {
	if m != nil {
		return m.TotalSuccessfulRequests
	}
	return 0
}

func (m *UpstreamEndpointStats) GetTotalRequestsInProgress() uint64 {
	if m != nil {
		return m.TotalRequestsInProgress
	}
	return 0
}

func (m *UpstreamEndpointStats) GetTotalErrorRequests() uint64 {
	if m != nil {
		return m.TotalErrorRequests
	}
	return 0
}

func (m *UpstreamEndpointStats) GetTotalIssuedRequests() uint64 {
	if m != nil {
		return m.TotalIssuedRequests
	}
	return 0
}

func (m *UpstreamEndpointStats) GetLoadMetricStats() []*EndpointLoadMetricStats {
	if m != nil {
		return m.LoadMetricStats
	}
	return nil
}

type EndpointLoadMetricStats struct {
	MetricName                    string   `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	NumRequestsFinishedWithMetric uint64   `protobuf:"varint,2,opt,name=num_requests_finished_with_metric,json=numRequestsFinishedWithMetric,proto3" json:"num_requests_finished_with_metric,omitempty"`
	TotalMetricValue              float64  `protobuf:"fixed64,3,opt,name=total_metric_value,json=totalMetricValue,proto3" json:"total_metric_value,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *EndpointLoadMetricStats) Reset()         { *m = EndpointLoadMetricStats{} }
func (m *EndpointLoadMetricStats) String() string { return proto.CompactTextString(m) }
func (*EndpointLoadMetricStats) ProtoMessage()    {}
func (*EndpointLoadMetricStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_5134f8f33d8f8d01, []int{2}
}

func (m *EndpointLoadMetricStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointLoadMetricStats.Unmarshal(m, b)
}
func (m *EndpointLoadMetricStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointLoadMetricStats.Marshal(b, m, deterministic)
}
func (m *EndpointLoadMetricStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointLoadMetricStats.Merge(m, src)
}
func (m *EndpointLoadMetricStats) XXX_Size() int {
	return xxx_messageInfo_EndpointLoadMetricStats.Size(m)
}
func (m *EndpointLoadMetricStats) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointLoadMetricStats.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointLoadMetricStats proto.InternalMessageInfo

func (m *EndpointLoadMetricStats) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *EndpointLoadMetricStats) GetNumRequestsFinishedWithMetric() uint64 {
	if m != nil {
		return m.NumRequestsFinishedWithMetric
	}
	return 0
}

func (m *EndpointLoadMetricStats) GetTotalMetricValue() float64 {
	if m != nil {
		return m.TotalMetricValue
	}
	return 0
}

type ClusterStats struct {
	ClusterName           string                          `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterServiceName    string                          `protobuf:"bytes,6,opt,name=cluster_service_name,json=clusterServiceName,proto3" json:"cluster_service_name,omitempty"`
	UpstreamLocalityStats []*UpstreamLocalityStats        `protobuf:"bytes,2,rep,name=upstream_locality_stats,json=upstreamLocalityStats,proto3" json:"upstream_locality_stats,omitempty"`
	TotalDroppedRequests  uint64                          `protobuf:"varint,3,opt,name=total_dropped_requests,json=totalDroppedRequests,proto3" json:"total_dropped_requests,omitempty"`
	DroppedRequests       []*ClusterStats_DroppedRequests `protobuf:"bytes,5,rep,name=dropped_requests,json=droppedRequests,proto3" json:"dropped_requests,omitempty"`
	LoadReportInterval    *duration.Duration              `protobuf:"bytes,4,opt,name=load_report_interval,json=loadReportInterval,proto3" json:"load_report_interval,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                        `json:"-"`
	XXX_unrecognized      []byte                          `json:"-"`
	XXX_sizecache         int32                           `json:"-"`
}

func (m *ClusterStats) Reset()         { *m = ClusterStats{} }
func (m *ClusterStats) String() string { return proto.CompactTextString(m) }
func (*ClusterStats) ProtoMessage()    {}
func (*ClusterStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_5134f8f33d8f8d01, []int{3}
}

func (m *ClusterStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterStats.Unmarshal(m, b)
}
func (m *ClusterStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterStats.Marshal(b, m, deterministic)
}
func (m *ClusterStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStats.Merge(m, src)
}
func (m *ClusterStats) XXX_Size() int {
	return xxx_messageInfo_ClusterStats.Size(m)
}
func (m *ClusterStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStats.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStats proto.InternalMessageInfo

func (m *ClusterStats) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterStats) GetClusterServiceName() string {
	if m != nil {
		return m.ClusterServiceName
	}
	return ""
}

func (m *ClusterStats) GetUpstreamLocalityStats() []*UpstreamLocalityStats {
	if m != nil {
		return m.UpstreamLocalityStats
	}
	return nil
}

func (m *ClusterStats) GetTotalDroppedRequests() uint64 {
	if m != nil {
		return m.TotalDroppedRequests
	}
	return 0
}

func (m *ClusterStats) GetDroppedRequests() []*ClusterStats_DroppedRequests {
	if m != nil {
		return m.DroppedRequests
	}
	return nil
}

func (m *ClusterStats) GetLoadReportInterval() *duration.Duration {
	if m != nil {
		return m.LoadReportInterval
	}
	return nil
}

type ClusterStats_DroppedRequests struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	DroppedCount         uint64   `protobuf:"varint,2,opt,name=dropped_count,json=droppedCount,proto3" json:"dropped_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterStats_DroppedRequests) Reset()         { *m = ClusterStats_DroppedRequests{} }
func (m *ClusterStats_DroppedRequests) String() string { return proto.CompactTextString(m) }
func (*ClusterStats_DroppedRequests) ProtoMessage()    {}
func (*ClusterStats_DroppedRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_5134f8f33d8f8d01, []int{3, 0}
}

func (m *ClusterStats_DroppedRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterStats_DroppedRequests.Unmarshal(m, b)
}
func (m *ClusterStats_DroppedRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterStats_DroppedRequests.Marshal(b, m, deterministic)
}
func (m *ClusterStats_DroppedRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStats_DroppedRequests.Merge(m, src)
}
func (m *ClusterStats_DroppedRequests) XXX_Size() int {
	return xxx_messageInfo_ClusterStats_DroppedRequests.Size(m)
}
func (m *ClusterStats_DroppedRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStats_DroppedRequests.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStats_DroppedRequests proto.InternalMessageInfo

func (m *ClusterStats_DroppedRequests) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ClusterStats_DroppedRequests) GetDroppedCount() uint64 {
	if m != nil {
		return m.DroppedCount
	}
	return 0
}

func init() {
	proto.RegisterType((*UpstreamLocalityStats)(nil), "envoy.api.v2.endpoint.UpstreamLocalityStats")
	proto.RegisterType((*UpstreamEndpointStats)(nil), "envoy.api.v2.endpoint.UpstreamEndpointStats")
	proto.RegisterType((*EndpointLoadMetricStats)(nil), "envoy.api.v2.endpoint.EndpointLoadMetricStats")
	proto.RegisterType((*ClusterStats)(nil), "envoy.api.v2.endpoint.ClusterStats")
	proto.RegisterType((*ClusterStats_DroppedRequests)(nil), "envoy.api.v2.endpoint.ClusterStats.DroppedRequests")
}

func init() {
	proto.RegisterFile("envoy/api/v2/endpoint/load_report.proto", fileDescriptor_5134f8f33d8f8d01)
}

var fileDescriptor_5134f8f33d8f8d01 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0x4b, 0x6f, 0xd3, 0x4a,
	0x18, 0x95, 0xd3, 0xb4, 0xc9, 0x9d, 0xb4, 0x4a, 0xef, 0xdc, 0xe6, 0x26, 0xcd, 0xbd, 0xd0, 0x90,
	0x2e, 0x88, 0x50, 0x65, 0x57, 0x69, 0x25, 0x10, 0xac, 0x48, 0x5b, 0x44, 0x45, 0x41, 0x95, 0x23,
	0x40, 0x02, 0x09, 0x6b, 0x6a, 0x4f, 0xd3, 0x91, 0x1c, 0x8f, 0x99, 0x87, 0x21, 0x3f, 0x82, 0x0d,
	0x6b, 0x7e, 0x05, 0x7b, 0xfe, 0x58, 0x57, 0xc8, 0xf3, 0x70, 0x1e, 0x4d, 0x25, 0x76, 0x48, 0xec,
	0xec, 0xef, 0x9c, 0xe3, 0xef, 0x75, 0x66, 0x0c, 0xee, 0xe3, 0x24, 0xa3, 0x13, 0x0f, 0xa5, 0xc4,
	0xcb, 0xfa, 0x1e, 0x4e, 0xa2, 0x94, 0x92, 0x44, 0x78, 0x31, 0x45, 0x51, 0xc0, 0x70, 0x4a, 0x99,
	0x70, 0x53, 0x46, 0x05, 0x85, 0x0d, 0x45, 0x74, 0x51, 0x4a, 0xdc, 0xac, 0xef, 0x5a, 0x62, 0x7b,
	0x67, 0x4e, 0x1f, 0x52, 0x86, 0x3d, 0x14, 0x45, 0x0c, 0x73, 0xae, 0x75, 0xed, 0xff, 0x6f, 0x12,
	0x2e, 0x10, 0xc7, 0x06, 0xbd, 0x3b, 0xa2, 0x74, 0x14, 0x63, 0x4f, 0xbd, 0x5d, 0xc8, 0x4b, 0x2f,
	0x92, 0x0c, 0x09, 0x42, 0x13, 0xab, 0x5e, 0xc4, 0xb9, 0x60, 0x32, 0x34, 0x35, 0xb5, 0x9b, 0x19,
	0x8a, 0x49, 0x84, 0x04, 0xf6, 0xec, 0x83, 0x06, 0xba, 0x5f, 0xca, 0xa0, 0xf1, 0x3a, 0xe5, 0x82,
	0x61, 0x34, 0x3e, 0xa3, 0x21, 0x8a, 0x89, 0x98, 0x0c, 0x05, 0x12, 0x1c, 0x3e, 0x04, 0xd5, 0xd8,
	0x04, 0x5a, 0x4e, 0xc7, 0xe9, 0xd5, 0xfa, 0xff, 0xb9, 0x73, 0x9d, 0xe5, 0x15, 0xba, 0x56, 0xe3,
	0x17, 0x64, 0xf8, 0x18, 0x6c, 0x0b, 0x2a, 0x50, 0x1c, 0x70, 0x19, 0x86, 0x98, 0xf3, 0x4b, 0x19,
	0x07, 0x0c, 0x7f, 0x94, 0x98, 0x0b, 0xde, 0x2a, 0x75, 0x9c, 0x5e, 0xd9, 0x6f, 0x2a, 0xc2, 0xb0,
	0xc0, 0x7d, 0x03, 0xc3, 0x27, 0xa0, 0xad, 0xb5, 0x56, 0x10, 0x90, 0x24, 0x48, 0x19, 0x1d, 0xe5,
	0x73, 0x6a, 0xad, 0xcc, 0x88, 0xad, 0xe4, 0x34, 0x39, 0x37, 0x30, 0xdc, 0x07, 0x5b, 0x5a, 0x8c,
	0x19, 0xa3, 0x6c, 0x9a, 0xb3, 0xac, 0x64, 0x50, 0x61, 0x27, 0x39, 0x54, 0xa4, 0xeb, 0x83, 0x86,
	0x56, 0x10, 0xce, 0x25, 0x8e, 0xa6, 0x92, 0xaa, 0x92, 0xfc, 0xa3, 0xc0, 0x53, 0x85, 0x15, 0x9a,
	0x77, 0xe0, 0x6f, 0xb5, 0xf3, 0x31, 0x16, 0x8c, 0x84, 0x01, 0xcf, 0x87, 0xd5, 0x5a, 0xed, 0xac,
	0xf4, 0x6a, 0x7d, 0xd7, 0x5d, 0xba, 0x7a, 0xf7, 0xc4, 0x3c, 0x9c, 0x51, 0x14, 0xbd, 0x54, 0x32,
	0x35, 0x62, 0xbf, 0x1e, 0xcf, 0x07, 0x60, 0x04, 0x9a, 0xd2, 0x2c, 0x23, 0xb0, 0x6a, 0x93, 0xa1,
	0xa2, 0x32, 0xec, 0xdd, 0x92, 0xc1, 0xae, 0xd0, 0x66, 0xd2, 0xdf, 0x6f, 0xc8, 0x65, 0x61, 0xd8,
	0x06, 0xd5, 0x94, 0x11, 0xca, 0xf2, 0xcd, 0xae, 0x75, 0x9c, 0xde, 0x86, 0x5f, 0xbc, 0x77, 0x7f,
	0xac, 0x4c, 0xfd, 0x30, 0xaf, 0x3a, 0x04, 0x15, 0xe3, 0x57, 0x63, 0x87, 0xf6, 0x12, 0x3b, 0x3c,
	0xd5, 0x0c, 0xdf, 0x52, 0xe1, 0x01, 0xa8, 0x8e, 0xb1, 0x40, 0x11, 0x12, 0x48, 0xe5, 0xaa, 0xf5,
	0x9b, 0xae, 0x76, 0xaa, 0x6b, 0x9d, 0xea, 0x0e, 0x95, 0x53, 0xfd, 0x82, 0xf8, 0x47, 0x38, 0xa8,
	0xf2, 0x5b, 0x1c, 0xd4, 0xfd, 0xee, 0x80, 0xe6, 0x2d, 0x64, 0xb8, 0x03, 0x6a, 0x26, 0x65, 0x82,
	0xc6, 0x58, 0x6d, 0xf1, 0x2f, 0x1f, 0xe8, 0xd0, 0x2b, 0x34, 0xc6, 0xf0, 0x39, 0xb8, 0x97, 0xc8,
	0xf1, 0x74, 0x72, 0x97, 0x24, 0x21, 0xfc, 0x0a, 0x47, 0xc1, 0x27, 0x22, 0xae, 0x4c, 0xb9, 0x66,
	0xfe, 0x77, 0x12, 0x39, 0xb6, 0x0d, 0x3d, 0x33, 0xb4, 0xb7, 0x44, 0x5c, 0xe9, 0x7c, 0x70, 0x0f,
	0xe8, 0x61, 0xd9, 0x1e, 0x33, 0x14, 0x4b, 0xac, 0xa6, 0xef, 0xf8, 0x9b, 0x0a, 0xd1, 0xc4, 0x37,
	0x79, 0xbc, 0xfb, 0xad, 0x0c, 0xd6, 0x8f, 0x62, 0xc9, 0x05, 0x66, 0xba, 0xd2, 0x07, 0x60, 0x3d,
	0xd4, 0xef, 0x33, 0xa5, 0x0e, 0x2a, 0xd7, 0x83, 0x32, 0x2b, 0x75, 0x1c, 0xbf, 0x66, 0x40, 0x55,
	0xf4, 0x3e, 0xd8, 0xb2, 0x5c, 0x8e, 0x59, 0x46, 0x42, 0xac, 0x35, 0x6b, 0xaa, 0x3d, 0x68, 0xb0,
	0xa1, 0x86, 0x94, 0x22, 0x99, 0x39, 0x65, 0xf6, 0xd6, 0x32, 0x5b, 0x28, 0xfd, 0xd2, 0x29, 0x9b,
	0xbb, 0x28, 0x07, 0xd5, 0xeb, 0xc1, 0xea, 0x57, 0xa7, 0x54, 0x75, 0xa6, 0xe7, 0x6d, 0xfe, 0x26,
	0x3d, 0x04, 0xff, 0xea, 0x61, 0x44, 0x8c, 0xa6, 0xe9, 0xac, 0x49, 0xb4, 0x1d, 0xb5, 0xe7, 0x8e,
	0x35, 0x58, 0xb8, 0xe4, 0x03, 0xd8, 0xbc, 0xc1, 0xd7, 0x26, 0x39, 0xb8, 0xa5, 0xbc, 0xd9, 0x11,
	0xba, 0x0b, 0x9f, 0xf3, 0xeb, 0xd1, 0xc2, 0xf7, 0x5f, 0x80, 0xad, 0x99, 0x7f, 0x57, 0x40, 0x12,
	0x81, 0x59, 0x86, 0x62, 0xe5, 0xf5, 0x5a, 0x7f, 0xfb, 0xc6, 0x29, 0x3d, 0x36, 0xff, 0x1b, 0x1f,
	0xe6, 0x32, 0x5f, 0xa9, 0x4e, 0x8d, 0xa8, 0xfd, 0x1e, 0xd4, 0x17, 0xeb, 0xdf, 0x05, 0xd5, 0x10,
	0x09, 0x3c, 0xa2, 0x6c, 0xb2, 0xb8, 0xbf, 0x02, 0x80, 0xbb, 0x60, 0xc3, 0x36, 0x19, 0x52, 0x99,
	0x08, 0xe3, 0xae, 0x75, 0x13, 0x3c, 0xca, 0x63, 0x83, 0x47, 0x60, 0x97, 0x50, 0xdd, 0x73, 0xca,
	0xe8, 0xe7, 0xc9, 0xf2, 0xf6, 0x07, 0xf5, 0xb3, 0xa2, 0xae, 0xf3, 0xbc, 0xe8, 0x73, 0xe7, 0x62,
	0x4d, 0x55, 0x7f, 0xf0, 0x33, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x92, 0x77, 0xb5, 0xbc, 0x07, 0x00,
	0x00,
}
