// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v2/core/protocol.proto

package envoy_api_v2_core

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TcpProtocolOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TcpProtocolOptions) Reset()         { *m = TcpProtocolOptions{} }
func (m *TcpProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*TcpProtocolOptions) ProtoMessage()    {}
func (*TcpProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d86476e078060b60, []int{0}
}

func (m *TcpProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpProtocolOptions.Unmarshal(m, b)
}
func (m *TcpProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpProtocolOptions.Marshal(b, m, deterministic)
}
func (m *TcpProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpProtocolOptions.Merge(m, src)
}
func (m *TcpProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_TcpProtocolOptions.Size(m)
}
func (m *TcpProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TcpProtocolOptions proto.InternalMessageInfo

type HttpProtocolOptions struct {
	IdleTimeout          *duration.Duration    `protobuf:"bytes,1,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	MaxHeadersCount      *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=max_headers_count,json=maxHeadersCount,proto3" json:"max_headers_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HttpProtocolOptions) Reset()         { *m = HttpProtocolOptions{} }
func (m *HttpProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*HttpProtocolOptions) ProtoMessage()    {}
func (*HttpProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d86476e078060b60, []int{1}
}

func (m *HttpProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpProtocolOptions.Unmarshal(m, b)
}
func (m *HttpProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpProtocolOptions.Marshal(b, m, deterministic)
}
func (m *HttpProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpProtocolOptions.Merge(m, src)
}
func (m *HttpProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_HttpProtocolOptions.Size(m)
}
func (m *HttpProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_HttpProtocolOptions proto.InternalMessageInfo

func (m *HttpProtocolOptions) GetIdleTimeout() *duration.Duration {
	if m != nil {
		return m.IdleTimeout
	}
	return nil
}

func (m *HttpProtocolOptions) GetMaxHeadersCount() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxHeadersCount
	}
	return nil
}

type Http1ProtocolOptions struct {
	AllowAbsoluteUrl      *wrappers.BoolValue                   `protobuf:"bytes,1,opt,name=allow_absolute_url,json=allowAbsoluteUrl,proto3" json:"allow_absolute_url,omitempty"`
	AcceptHttp_10         bool                                  `protobuf:"varint,2,opt,name=accept_http_10,json=acceptHttp10,proto3" json:"accept_http_10,omitempty"`
	DefaultHostForHttp_10 string                                `protobuf:"bytes,3,opt,name=default_host_for_http_10,json=defaultHostForHttp10,proto3" json:"default_host_for_http_10,omitempty"`
	HeaderKeyFormat       *Http1ProtocolOptions_HeaderKeyFormat `protobuf:"bytes,4,opt,name=header_key_format,json=headerKeyFormat,proto3" json:"header_key_format,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                              `json:"-"`
	XXX_unrecognized      []byte                                `json:"-"`
	XXX_sizecache         int32                                 `json:"-"`
}

func (m *Http1ProtocolOptions) Reset()         { *m = Http1ProtocolOptions{} }
func (m *Http1ProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*Http1ProtocolOptions) ProtoMessage()    {}
func (*Http1ProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d86476e078060b60, []int{2}
}

func (m *Http1ProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http1ProtocolOptions.Unmarshal(m, b)
}
func (m *Http1ProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http1ProtocolOptions.Marshal(b, m, deterministic)
}
func (m *Http1ProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http1ProtocolOptions.Merge(m, src)
}
func (m *Http1ProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_Http1ProtocolOptions.Size(m)
}
func (m *Http1ProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Http1ProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Http1ProtocolOptions proto.InternalMessageInfo

func (m *Http1ProtocolOptions) GetAllowAbsoluteUrl() *wrappers.BoolValue {
	if m != nil {
		return m.AllowAbsoluteUrl
	}
	return nil
}

func (m *Http1ProtocolOptions) GetAcceptHttp_10() bool {
	if m != nil {
		return m.AcceptHttp_10
	}
	return false
}

func (m *Http1ProtocolOptions) GetDefaultHostForHttp_10() string {
	if m != nil {
		return m.DefaultHostForHttp_10
	}
	return ""
}

func (m *Http1ProtocolOptions) GetHeaderKeyFormat() *Http1ProtocolOptions_HeaderKeyFormat {
	if m != nil {
		return m.HeaderKeyFormat
	}
	return nil
}

type Http1ProtocolOptions_HeaderKeyFormat struct {
	// Types that are valid to be assigned to HeaderFormat:
	//	*Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords_
	HeaderFormat         isHttp1ProtocolOptions_HeaderKeyFormat_HeaderFormat `protobuf_oneof:"header_format"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *Http1ProtocolOptions_HeaderKeyFormat) Reset()         { *m = Http1ProtocolOptions_HeaderKeyFormat{} }
func (m *Http1ProtocolOptions_HeaderKeyFormat) String() string { return proto.CompactTextString(m) }
func (*Http1ProtocolOptions_HeaderKeyFormat) ProtoMessage()    {}
func (*Http1ProtocolOptions_HeaderKeyFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_d86476e078060b60, []int{2, 0}
}

func (m *Http1ProtocolOptions_HeaderKeyFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat.Unmarshal(m, b)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat.Marshal(b, m, deterministic)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat.Merge(m, src)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat) XXX_Size() int {
	return xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat.Size(m)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat.DiscardUnknown(m)
}

var xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat proto.InternalMessageInfo

type isHttp1ProtocolOptions_HeaderKeyFormat_HeaderFormat interface {
	isHttp1ProtocolOptions_HeaderKeyFormat_HeaderFormat()
}

type Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords_ struct {
	ProperCaseWords *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords `protobuf:"bytes,1,opt,name=proper_case_words,json=properCaseWords,proto3,oneof"`
}

func (*Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords_) isHttp1ProtocolOptions_HeaderKeyFormat_HeaderFormat() {
}

func (m *Http1ProtocolOptions_HeaderKeyFormat) GetHeaderFormat() isHttp1ProtocolOptions_HeaderKeyFormat_HeaderFormat {
	if m != nil {
		return m.HeaderFormat
	}
	return nil
}

func (m *Http1ProtocolOptions_HeaderKeyFormat) GetProperCaseWords() *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords {
	if x, ok := m.GetHeaderFormat().(*Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords_); ok {
		return x.ProperCaseWords
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Http1ProtocolOptions_HeaderKeyFormat) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords_)(nil),
	}
}

type Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) Reset() {
	*m = Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords{}
}
func (m *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) String() string {
	return proto.CompactTextString(m)
}
func (*Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) ProtoMessage() {}
func (*Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) Descriptor() ([]byte, []int) {
	return fileDescriptor_d86476e078060b60, []int{2, 0, 0}
}

func (m *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords.Unmarshal(m, b)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords.Marshal(b, m, deterministic)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords.Merge(m, src)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) XXX_Size() int {
	return xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords.Size(m)
}
func (m *Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords) XXX_DiscardUnknown() {
	xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords.DiscardUnknown(m)
}

var xxx_messageInfo_Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords proto.InternalMessageInfo

type Http2ProtocolOptions struct {
	HpackTableSize                               *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=hpack_table_size,json=hpackTableSize,proto3" json:"hpack_table_size,omitempty"`
	MaxConcurrentStreams                         *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=max_concurrent_streams,json=maxConcurrentStreams,proto3" json:"max_concurrent_streams,omitempty"`
	InitialStreamWindowSize                      *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=initial_stream_window_size,json=initialStreamWindowSize,proto3" json:"initial_stream_window_size,omitempty"`
	InitialConnectionWindowSize                  *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=initial_connection_window_size,json=initialConnectionWindowSize,proto3" json:"initial_connection_window_size,omitempty"`
	AllowConnect                                 bool                  `protobuf:"varint,5,opt,name=allow_connect,json=allowConnect,proto3" json:"allow_connect,omitempty"`
	AllowMetadata                                bool                  `protobuf:"varint,6,opt,name=allow_metadata,json=allowMetadata,proto3" json:"allow_metadata,omitempty"`
	MaxOutboundFrames                            *wrappers.UInt32Value `protobuf:"bytes,7,opt,name=max_outbound_frames,json=maxOutboundFrames,proto3" json:"max_outbound_frames,omitempty"`
	MaxOutboundControlFrames                     *wrappers.UInt32Value `protobuf:"bytes,8,opt,name=max_outbound_control_frames,json=maxOutboundControlFrames,proto3" json:"max_outbound_control_frames,omitempty"`
	MaxConsecutiveInboundFramesWithEmptyPayload  *wrappers.UInt32Value `protobuf:"bytes,9,opt,name=max_consecutive_inbound_frames_with_empty_payload,json=maxConsecutiveInboundFramesWithEmptyPayload,proto3" json:"max_consecutive_inbound_frames_with_empty_payload,omitempty"`
	MaxInboundPriorityFramesPerStream            *wrappers.UInt32Value `protobuf:"bytes,10,opt,name=max_inbound_priority_frames_per_stream,json=maxInboundPriorityFramesPerStream,proto3" json:"max_inbound_priority_frames_per_stream,omitempty"`
	MaxInboundWindowUpdateFramesPerDataFrameSent *wrappers.UInt32Value `protobuf:"bytes,11,opt,name=max_inbound_window_update_frames_per_data_frame_sent,json=maxInboundWindowUpdateFramesPerDataFrameSent,proto3" json:"max_inbound_window_update_frames_per_data_frame_sent,omitempty"`
	StreamErrorOnInvalidHttpMessaging            bool                  `protobuf:"varint,12,opt,name=stream_error_on_invalid_http_messaging,json=streamErrorOnInvalidHttpMessaging,proto3" json:"stream_error_on_invalid_http_messaging,omitempty"`
	XXX_NoUnkeyedLiteral                         struct{}              `json:"-"`
	XXX_unrecognized                             []byte                `json:"-"`
	XXX_sizecache                                int32                 `json:"-"`
}

func (m *Http2ProtocolOptions) Reset()         { *m = Http2ProtocolOptions{} }
func (m *Http2ProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*Http2ProtocolOptions) ProtoMessage()    {}
func (*Http2ProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d86476e078060b60, []int{3}
}

func (m *Http2ProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http2ProtocolOptions.Unmarshal(m, b)
}
func (m *Http2ProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http2ProtocolOptions.Marshal(b, m, deterministic)
}
func (m *Http2ProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http2ProtocolOptions.Merge(m, src)
}
func (m *Http2ProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_Http2ProtocolOptions.Size(m)
}
func (m *Http2ProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Http2ProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Http2ProtocolOptions proto.InternalMessageInfo

func (m *Http2ProtocolOptions) GetHpackTableSize() *wrappers.UInt32Value {
	if m != nil {
		return m.HpackTableSize
	}
	return nil
}

func (m *Http2ProtocolOptions) GetMaxConcurrentStreams() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxConcurrentStreams
	}
	return nil
}

func (m *Http2ProtocolOptions) GetInitialStreamWindowSize() *wrappers.UInt32Value {
	if m != nil {
		return m.InitialStreamWindowSize
	}
	return nil
}

func (m *Http2ProtocolOptions) GetInitialConnectionWindowSize() *wrappers.UInt32Value {
	if m != nil {
		return m.InitialConnectionWindowSize
	}
	return nil
}

func (m *Http2ProtocolOptions) GetAllowConnect() bool {
	if m != nil {
		return m.AllowConnect
	}
	return false
}

func (m *Http2ProtocolOptions) GetAllowMetadata() bool {
	if m != nil {
		return m.AllowMetadata
	}
	return false
}

func (m *Http2ProtocolOptions) GetMaxOutboundFrames() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxOutboundFrames
	}
	return nil
}

func (m *Http2ProtocolOptions) GetMaxOutboundControlFrames() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxOutboundControlFrames
	}
	return nil
}

func (m *Http2ProtocolOptions) GetMaxConsecutiveInboundFramesWithEmptyPayload() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxConsecutiveInboundFramesWithEmptyPayload
	}
	return nil
}

func (m *Http2ProtocolOptions) GetMaxInboundPriorityFramesPerStream() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxInboundPriorityFramesPerStream
	}
	return nil
}

func (m *Http2ProtocolOptions) GetMaxInboundWindowUpdateFramesPerDataFrameSent() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxInboundWindowUpdateFramesPerDataFrameSent
	}
	return nil
}

func (m *Http2ProtocolOptions) GetStreamErrorOnInvalidHttpMessaging() bool {
	if m != nil {
		return m.StreamErrorOnInvalidHttpMessaging
	}
	return false
}

type GrpcProtocolOptions struct {
	Http2ProtocolOptions *Http2ProtocolOptions `protobuf:"bytes,1,opt,name=http2_protocol_options,json=http2ProtocolOptions,proto3" json:"http2_protocol_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GrpcProtocolOptions) Reset()         { *m = GrpcProtocolOptions{} }
func (m *GrpcProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*GrpcProtocolOptions) ProtoMessage()    {}
func (*GrpcProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d86476e078060b60, []int{4}
}

func (m *GrpcProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcProtocolOptions.Unmarshal(m, b)
}
func (m *GrpcProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcProtocolOptions.Marshal(b, m, deterministic)
}
func (m *GrpcProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcProtocolOptions.Merge(m, src)
}
func (m *GrpcProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_GrpcProtocolOptions.Size(m)
}
func (m *GrpcProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcProtocolOptions proto.InternalMessageInfo

func (m *GrpcProtocolOptions) GetHttp2ProtocolOptions() *Http2ProtocolOptions {
	if m != nil {
		return m.Http2ProtocolOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*TcpProtocolOptions)(nil), "envoy.api.v2.core.TcpProtocolOptions")
	proto.RegisterType((*HttpProtocolOptions)(nil), "envoy.api.v2.core.HttpProtocolOptions")
	proto.RegisterType((*Http1ProtocolOptions)(nil), "envoy.api.v2.core.Http1ProtocolOptions")
	proto.RegisterType((*Http1ProtocolOptions_HeaderKeyFormat)(nil), "envoy.api.v2.core.Http1ProtocolOptions.HeaderKeyFormat")
	proto.RegisterType((*Http1ProtocolOptions_HeaderKeyFormat_ProperCaseWords)(nil), "envoy.api.v2.core.Http1ProtocolOptions.HeaderKeyFormat.ProperCaseWords")
	proto.RegisterType((*Http2ProtocolOptions)(nil), "envoy.api.v2.core.Http2ProtocolOptions")
	proto.RegisterType((*GrpcProtocolOptions)(nil), "envoy.api.v2.core.GrpcProtocolOptions")
}

func init() { proto.RegisterFile("envoy/api/v2/core/protocol.proto", fileDescriptor_d86476e078060b60) }

var fileDescriptor_d86476e078060b60 = []byte{
	// 917 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4b, 0x73, 0x1b, 0x35,
	0x1c, 0x67, 0xeb, 0xd2, 0x24, 0xca, 0xc3, 0xf5, 0xc6, 0xd3, 0x2e, 0x2e, 0x53, 0x52, 0x03, 0x25,
	0x13, 0x98, 0x75, 0xe3, 0x32, 0x70, 0xe1, 0x82, 0xdd, 0xa6, 0xce, 0x30, 0x9d, 0x98, 0x4d, 0x42,
	0x4e, 0x8c, 0x46, 0xde, 0x55, 0x62, 0xd1, 0x5d, 0xfd, 0x35, 0x5a, 0xad, 0x1f, 0x3d, 0x73, 0xe1,
	0xc8, 0x97, 0xe0, 0xce, 0xa7, 0xe1, 0xab, 0x30, 0xb9, 0x98, 0xd1, 0x63, 0x83, 0x63, 0x17, 0x26,
	0xe9, 0xc9, 0x5e, 0xe9, 0xf7, 0x92, 0xf4, 0xd7, 0x5f, 0x68, 0x87, 0xf2, 0x11, 0x4c, 0x5b, 0x44,
	0xb0, 0xd6, 0xa8, 0xdd, 0x8a, 0x41, 0xd2, 0x96, 0x90, 0xa0, 0x20, 0x86, 0x34, 0x34, 0x7f, 0xfc,
	0x9a, 0x41, 0x84, 0x44, 0xb0, 0x70, 0xd4, 0x0e, 0x35, 0xa2, 0xf1, 0xf8, 0x02, 0xe0, 0x22, 0x75,
	0xc8, 0x41, 0x71, 0xde, 0x4a, 0x0a, 0x49, 0x14, 0x03, 0x6e, 0x29, 0xcb, 0xf3, 0x63, 0x49, 0x84,
	0xa0, 0x32, 0x77, 0xf3, 0x0f, 0x47, 0x24, 0x65, 0x09, 0x51, 0xb4, 0x55, 0xfe, 0xb1, 0x13, 0xcd,
	0x3a, 0xf2, 0x4f, 0x62, 0xd1, 0x77, 0x01, 0x8e, 0x84, 0xd6, 0xcc, 0x9b, 0x7f, 0x78, 0x68, 0xbb,
	0xa7, 0xd4, 0xe2, 0xb8, 0xff, 0x1d, 0xda, 0x60, 0x49, 0x4a, 0xb1, 0x62, 0x19, 0x85, 0x42, 0x05,
	0xde, 0x8e, 0xb7, 0xbb, 0xde, 0xfe, 0x28, 0xb4, 0xee, 0x61, 0xe9, 0x1e, 0xbe, 0x70, 0xe9, 0xa2,
	0x75, 0x0d, 0x3f, 0xb1, 0x68, 0xff, 0x47, 0x54, 0xcb, 0xc8, 0x04, 0x0f, 0x29, 0x49, 0xa8, 0xcc,
	0x71, 0x0c, 0x05, 0x57, 0xc1, 0x1d, 0x23, 0xf1, 0xf1, 0x92, 0xc4, 0xe9, 0x21, 0x57, 0xcf, 0xdb,
	0x3f, 0x91, 0xb4, 0xa0, 0x9d, 0x95, 0xcb, 0xce, 0xdd, 0xbd, 0x3b, 0xbb, 0x5e, 0x54, 0xcd, 0xc8,
	0xa4, 0x67, 0xe9, 0x5d, 0xcd, 0x6e, 0xfe, 0x55, 0x41, 0x75, 0x1d, 0x74, 0x7f, 0x31, 0x69, 0x0f,
	0xf9, 0x24, 0x4d, 0x61, 0x8c, 0xc9, 0x20, 0x87, 0xb4, 0x50, 0x14, 0x17, 0x32, 0x75, 0x79, 0x1b,
	0x4b, 0x66, 0x1d, 0x80, 0xd4, 0x58, 0x45, 0xf7, 0x0d, 0xeb, 0x7b, 0x47, 0x3a, 0x95, 0xa9, 0xff,
	0x19, 0xda, 0x22, 0x71, 0x4c, 0x85, 0xc2, 0x43, 0xa5, 0x04, 0xde, 0x7f, 0x66, 0x22, 0xaf, 0x46,
	0x1b, 0x76, 0xd4, 0xb8, 0x3f, 0xf3, 0xbf, 0x41, 0x41, 0x42, 0xcf, 0x49, 0x91, 0x2a, 0x3c, 0x84,
	0x5c, 0xe1, 0x73, 0x90, 0x57, 0xf8, 0xca, 0x8e, 0xb7, 0xbb, 0x16, 0xd5, 0xdd, 0x7c, 0x0f, 0x72,
	0x75, 0x00, 0xd2, 0xf1, 0x62, 0x54, 0xb3, 0xfb, 0x81, 0xdf, 0xd0, 0xa9, 0x66, 0x65, 0x44, 0x05,
	0x77, 0x4d, 0xcc, 0x6f, 0xc3, 0xa5, 0x3a, 0x08, 0xdf, 0xb5, 0xd6, 0xd0, 0xee, 0xc8, 0x0f, 0x74,
	0x7a, 0x60, 0xe8, 0x51, 0x75, 0x78, 0x7d, 0xa0, 0xf1, 0xa7, 0x87, 0xaa, 0x0b, 0x20, 0xbf, 0x40,
	0x35, 0x21, 0x41, 0x50, 0x89, 0x63, 0x92, 0x53, 0x3c, 0x06, 0x99, 0xe4, 0x6e, 0x7f, 0x5e, 0xbd,
	0xa7, 0x71, 0xd8, 0x37, 0x82, 0x5d, 0x92, 0xd3, 0x33, 0x2d, 0xd7, 0xfb, 0x20, 0xaa, 0x8a, 0xeb,
	0x43, 0x8d, 0x1a, 0xaa, 0x2e, 0xa0, 0x3a, 0x75, 0xb4, 0xe9, 0xb6, 0xc0, 0x2e, 0xdf, 0xaf, 0xfc,
	0xdd, 0xf1, 0x9a, 0xbf, 0xad, 0xd9, 0x93, 0x6d, 0x2f, 0x9e, 0xec, 0x01, 0xba, 0x3f, 0x14, 0x24,
	0x7e, 0x83, 0x15, 0x19, 0xa4, 0x14, 0xe7, 0xec, 0x2d, 0x75, 0xb9, 0xff, 0xb7, 0x88, 0xa2, 0x2d,
	0xc3, 0x3a, 0xd1, 0xa4, 0x63, 0xf6, 0x96, 0xfa, 0x04, 0x3d, 0xd0, 0xd5, 0x18, 0x03, 0x8f, 0x0b,
	0x29, 0x29, 0x57, 0x38, 0x57, 0x92, 0x92, 0x2c, 0xbf, 0x51, 0x49, 0x6e, 0x5e, 0x76, 0xd0, 0xde,
	0x6a, 0x30, 0x9b, 0xcd, 0x66, 0x2b, 0xbb, 0x5e, 0x54, 0xcf, 0xc8, 0xa4, 0x7b, 0xa5, 0x74, 0x6c,
	0x85, 0xfc, 0x5f, 0x50, 0x83, 0x71, 0xa6, 0x18, 0x49, 0x9d, 0x36, 0x1e, 0x33, 0x9e, 0xc0, 0xd8,
	0x86, 0xae, 0xdc, 0xc0, 0xa6, 0x7a, 0xd9, 0xd9, 0xd8, 0x43, 0xce, 0x66, 0x36, 0xab, 0x44, 0x0f,
	0x9d, 0xa0, 0xb5, 0x38, 0x33, 0x72, 0x66, 0x39, 0x12, 0x3d, 0x2e, 0xbd, 0x62, 0xe0, 0x9c, 0xc6,
	0x7a, 0xb7, 0xae, 0xf9, 0xdd, 0x7d, 0x1f, 0xbf, 0x47, 0x4e, 0xb4, 0x7b, 0xa5, 0x39, 0xe7, 0xf9,
	0x29, 0xda, 0xb4, 0x97, 0xcc, 0x39, 0x06, 0x1f, 0xba, 0x9b, 0xa1, 0x07, 0x1d, 0xc3, 0xff, 0x1c,
	0x6d, 0x59, 0x50, 0x46, 0x15, 0x49, 0x88, 0x22, 0xc1, 0x3d, 0x83, 0xb2, 0xd4, 0xd7, 0x6e, 0xd0,
	0x3f, 0x45, 0xdb, 0xfa, 0x38, 0xa0, 0x50, 0x03, 0x28, 0x78, 0x82, 0xcf, 0x25, 0xc9, 0x68, 0x1e,
	0xac, 0xdc, 0xa6, 0x3d, 0xe8, 0xf6, 0x72, 0xe4, 0x04, 0x0e, 0x0c, 0xdf, 0x4f, 0xd0, 0xa3, 0x6b,
	0xb2, 0x31, 0x70, 0x25, 0x21, 0x2d, 0xe5, 0x57, 0x6f, 0x23, 0x1f, 0xcc, 0xc9, 0x77, 0xad, 0x8e,
	0x73, 0xf9, 0xd5, 0x43, 0xfb, 0xae, 0x98, 0x72, 0x1a, 0x17, 0x8a, 0x8d, 0x28, 0x66, 0x7c, 0x7e,
	0x21, 0x78, 0xcc, 0xd4, 0x10, 0xd3, 0x4c, 0xa8, 0x29, 0x16, 0x64, 0x9a, 0x02, 0x49, 0x82, 0xb5,
	0x1b, 0x54, 0xed, 0x97, 0xb6, 0xb0, 0x4a, 0xd5, 0x43, 0x3e, 0xb7, 0xb8, 0x33, 0xa6, 0x86, 0x2f,
	0xb5, 0x62, 0xdf, 0x0a, 0xfa, 0x80, 0x9e, 0xea, 0x14, 0xa5, 0xb3, 0x90, 0x0c, 0x24, 0x53, 0xd3,
	0x32, 0x82, 0xbe, 0xec, 0xb6, 0x0e, 0x03, 0x74, 0x03, 0xeb, 0x27, 0x19, 0x99, 0x38, 0xbf, 0xbe,
	0x53, 0xb2, 0xbe, 0x7d, 0x2a, 0x6d, 0xf9, 0xf9, 0xbf, 0x7b, 0xe8, 0xeb, 0x79, 0x47, 0x57, 0x6e,
	0x85, 0xd0, 0x2f, 0xcc, 0xbc, 0xad, 0x3e, 0x62, 0xfb, 0x8d, 0x73, 0xca, 0x55, 0xb0, 0x7e, 0x9b,
	0x7d, 0xff, 0xea, 0xdf, 0x20, 0xb6, 0xf8, 0x4e, 0x8d, 0xfe, 0x55, 0x98, 0x17, 0x44, 0x11, 0xf3,
	0x71, 0x4c, 0xb9, 0x7e, 0x65, 0x9e, 0xba, 0xcb, 0x46, 0xa5, 0x04, 0x89, 0x81, 0x63, 0xc6, 0xcd,
	0xab, 0x67, 0x1b, 0x72, 0x46, 0xf3, 0x9c, 0x5c, 0x30, 0x7e, 0x11, 0x6c, 0x98, 0x3a, 0x7c, 0x62,
	0xd1, 0x2f, 0x35, 0xf8, 0x88, 0x1f, 0x5a, 0xa8, 0xee, 0x3c, 0xaf, 0x4b, 0x60, 0x53, 0xa1, 0xed,
	0x57, 0x52, 0xc4, 0x8b, 0x9d, 0xe8, 0x67, 0xf4, 0x40, 0x2b, 0xb6, 0x71, 0xf9, 0x7e, 0x63, 0xb0,
	0x33, 0xae, 0x1f, 0x7d, 0xf1, 0x1f, 0x7d, 0x74, 0xb1, 0xa5, 0x45, 0xf5, 0xe1, 0x3b, 0x46, 0x3b,
	0x6d, 0xf4, 0x09, 0x03, 0x2b, 0x21, 0x24, 0x4c, 0xa6, 0xcb, 0x6a, 0x9d, 0xcd, 0x92, 0x63, 0x7e,
	0xfb, 0xde, 0xe0, 0x9e, 0x89, 0xf2, 0xfc, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x68, 0xb1,
	0x88, 0x65, 0x08, 0x00, 0x00,
}
