// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/type/matcher/v3alpha/metadata.proto

package envoy_type_matcher_v3alpha

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetadataMatcher struct {
	Filter               string                         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Path                 []*MetadataMatcher_PathSegment `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Value                *ValueMatcher                  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *MetadataMatcher) Reset()         { *m = MetadataMatcher{} }
func (m *MetadataMatcher) String() string { return proto.CompactTextString(m) }
func (*MetadataMatcher) ProtoMessage()    {}
func (*MetadataMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_d306cd29ee202178, []int{0}
}

func (m *MetadataMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataMatcher.Unmarshal(m, b)
}
func (m *MetadataMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataMatcher.Marshal(b, m, deterministic)
}
func (m *MetadataMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataMatcher.Merge(m, src)
}
func (m *MetadataMatcher) XXX_Size() int {
	return xxx_messageInfo_MetadataMatcher.Size(m)
}
func (m *MetadataMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataMatcher proto.InternalMessageInfo

func (m *MetadataMatcher) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *MetadataMatcher) GetPath() []*MetadataMatcher_PathSegment {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *MetadataMatcher) GetValue() *ValueMatcher {
	if m != nil {
		return m.Value
	}
	return nil
}

type MetadataMatcher_PathSegment struct {
	// Types that are valid to be assigned to Segment:
	//	*MetadataMatcher_PathSegment_Key
	Segment              isMetadataMatcher_PathSegment_Segment `protobuf_oneof:"segment"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *MetadataMatcher_PathSegment) Reset()         { *m = MetadataMatcher_PathSegment{} }
func (m *MetadataMatcher_PathSegment) String() string { return proto.CompactTextString(m) }
func (*MetadataMatcher_PathSegment) ProtoMessage()    {}
func (*MetadataMatcher_PathSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_d306cd29ee202178, []int{0, 0}
}

func (m *MetadataMatcher_PathSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataMatcher_PathSegment.Unmarshal(m, b)
}
func (m *MetadataMatcher_PathSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataMatcher_PathSegment.Marshal(b, m, deterministic)
}
func (m *MetadataMatcher_PathSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataMatcher_PathSegment.Merge(m, src)
}
func (m *MetadataMatcher_PathSegment) XXX_Size() int {
	return xxx_messageInfo_MetadataMatcher_PathSegment.Size(m)
}
func (m *MetadataMatcher_PathSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataMatcher_PathSegment.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataMatcher_PathSegment proto.InternalMessageInfo

type isMetadataMatcher_PathSegment_Segment interface {
	isMetadataMatcher_PathSegment_Segment()
}

type MetadataMatcher_PathSegment_Key struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3,oneof"`
}

func (*MetadataMatcher_PathSegment_Key) isMetadataMatcher_PathSegment_Segment() {}

func (m *MetadataMatcher_PathSegment) GetSegment() isMetadataMatcher_PathSegment_Segment {
	if m != nil {
		return m.Segment
	}
	return nil
}

func (m *MetadataMatcher_PathSegment) GetKey() string {
	if x, ok := m.GetSegment().(*MetadataMatcher_PathSegment_Key); ok {
		return x.Key
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetadataMatcher_PathSegment) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetadataMatcher_PathSegment_Key)(nil),
	}
}

func init() {
	proto.RegisterType((*MetadataMatcher)(nil), "envoy.type.matcher.v3alpha.MetadataMatcher")
	proto.RegisterType((*MetadataMatcher_PathSegment)(nil), "envoy.type.matcher.v3alpha.MetadataMatcher.PathSegment")
}

func init() {
	proto.RegisterFile("envoy/type/matcher/v3alpha/metadata.proto", fileDescriptor_d306cd29ee202178)
}

var fileDescriptor_d306cd29ee202178 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3d, 0x4b, 0xf4, 0x40,
	0x10, 0xc7, 0x9f, 0x49, 0xee, 0xed, 0xd9, 0xe0, 0x0b, 0x69, 0x0c, 0xb1, 0x30, 0x58, 0x48, 0x6c,
	0x36, 0x70, 0x57, 0x08, 0xda, 0x6d, 0x75, 0xcd, 0x41, 0x88, 0x68, 0x3f, 0x7a, 0xa3, 0x09, 0x26,
	0x97, 0x10, 0xc7, 0x60, 0xbe, 0x82, 0x8d, 0xe0, 0xa7, 0x95, 0xab, 0x24, 0xd9, 0x3d, 0x90, 0x03,
	0xd3, 0x2d, 0xb3, 0x3f, 0x7e, 0xff, 0xff, 0x8c, 0xb8, 0xa4, 0x4d, 0x53, 0xb6, 0x11, 0xb7, 0x15,
	0x45, 0x05, 0xf2, 0x63, 0x4a, 0x75, 0xd4, 0x2c, 0x30, 0xaf, 0x52, 0x8c, 0x0a, 0x62, 0x5c, 0x23,
	0xa3, 0xac, 0xea, 0x92, 0x4b, 0xd7, 0xef, 0x51, 0xd9, 0xa1, 0xd2, 0xa0, 0xd2, 0xa0, 0xfe, 0xc5,
	0x80, 0xa6, 0xc1, 0xfc, 0x8d, 0xb4, 0xc3, 0x3f, 0x69, 0x30, 0xcf, 0xd6, 0xc8, 0x14, 0xed, 0x1e,
	0xfa, 0xe3, 0xfc, 0xd3, 0x12, 0x47, 0x2b, 0x93, 0xb7, 0xd2, 0x02, 0xf7, 0x4c, 0x4c, 0x9e, 0xb2,
	0x9c, 0xa9, 0xf6, 0x20, 0x80, 0xf0, 0xbf, 0x9a, 0x6e, 0xd5, 0xa8, 0xb6, 0x02, 0x48, 0xcc, 0xd8,
	0xbd, 0x13, 0xa3, 0x0a, 0x39, 0xf5, 0xac, 0xc0, 0x0e, 0x9d, 0xf9, 0x95, 0xfc, 0xbb, 0xa0, 0xdc,
	0x73, 0xcb, 0x18, 0x39, 0xbd, 0xa5, 0xe7, 0x82, 0x36, 0xac, 0x66, 0x5b, 0x35, 0xfe, 0x02, 0x6b,
	0x06, 0x49, 0xaf, 0x73, 0x97, 0x62, 0xdc, 0x77, 0xf6, 0xec, 0x00, 0x42, 0x67, 0x1e, 0x0e, 0x79,
	0xef, 0x3b, 0xd0, 0x48, 0x7b, 0xd1, 0x07, 0x58, 0xc7, 0x90, 0x68, 0x81, 0x7f, 0x2d, 0x9c, 0x5f,
	0x41, 0xee, 0xa9, 0xb0, 0x5f, 0xa8, 0xdd, 0xdb, 0x66, 0xf9, 0x2f, 0xe9, 0xa6, 0xea, 0x50, 0x4c,
	0x5f, 0x0d, 0x67, 0x7f, 0x2b, 0x50, 0x37, 0x22, 0xcc, 0x4a, 0x1d, 0x5d, 0xd5, 0xe5, 0x7b, 0x3b,
	0xd0, 0x42, 0x1d, 0xec, 0xd6, 0x8b, 0xbb, 0x63, 0xc6, 0xf0, 0x30, 0xe9, 0xaf, 0xba, 0xf8, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x4b, 0x60, 0x51, 0x69, 0xdf, 0x01, 0x00, 0x00,
}
