# Enabled rules
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.errorf]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.superfluous-else]
[rule.time-naming]
[rule.var-naming]
[rule.unexported-return]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.var-declaration]
[rule.use-any]

# Disabled rules
# https://github.com/grpc/grpc-go/issues/7444 to track TODO(s)
[rule.empty-block]
    Disabled = true
[rule.import-shadowing]
    Disabled = true

