# Enabled rules
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]

# Disabled rules
# https://github.com/grpc/grpc-go/issues/7444 to track TODO(s)
[rule.empty-block]
    Disabled = true
[rule.exported]
    Disabled = true # TODO: Enable after existing issues are fixed
[rule.redefines-builtin-id]
    Disabled = true # TODO: Enable after existing issues are fixed
[rule.package-comments]
    Disabled = true # TODO: Enable after existing issues are fixed
[rule.use-any]
    Disabled = true # TODO: Enable after existing issues are fixed