// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v3alpha/discovery.proto

package envoy_api_v3alpha

import (
	fmt "fmt"
	core "google.golang.org/grpc/xds/internal/proto/envoy/api/v3alpha/core"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscoveryRequest struct {
	VersionInfo          string         `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	Node                 *core.Node     `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	ResourceNames        []string       `protobuf:"bytes,3,rep,name=resource_names,json=resourceNames,proto3" json:"resource_names,omitempty"`
	TypeUrl              string         `protobuf:"bytes,4,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	ResponseNonce        string         `protobuf:"bytes,5,opt,name=response_nonce,json=responseNonce,proto3" json:"response_nonce,omitempty"`
	ErrorDetail          *status.Status `protobuf:"bytes,6,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DiscoveryRequest) Reset()         { *m = DiscoveryRequest{} }
func (m *DiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoveryRequest) ProtoMessage()    {}
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94ac02770f363096, []int{0}
}

func (m *DiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryRequest.Unmarshal(m, b)
}
func (m *DiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *DiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryRequest.Merge(m, src)
}
func (m *DiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoveryRequest.Size(m)
}
func (m *DiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryRequest proto.InternalMessageInfo

func (m *DiscoveryRequest) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *DiscoveryRequest) GetNode() *core.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *DiscoveryRequest) GetResourceNames() []string {
	if m != nil {
		return m.ResourceNames
	}
	return nil
}

func (m *DiscoveryRequest) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *DiscoveryRequest) GetResponseNonce() string {
	if m != nil {
		return m.ResponseNonce
	}
	return ""
}

func (m *DiscoveryRequest) GetErrorDetail() *status.Status {
	if m != nil {
		return m.ErrorDetail
	}
	return nil
}

type DiscoveryResponse struct {
	VersionInfo          string             `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	Resources            []*any.Any         `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Canary               bool               `protobuf:"varint,3,opt,name=canary,proto3" json:"canary,omitempty"`
	TypeUrl              string             `protobuf:"bytes,4,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Nonce                string             `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ControlPlane         *core.ControlPlane `protobuf:"bytes,6,opt,name=control_plane,json=controlPlane,proto3" json:"control_plane,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DiscoveryResponse) Reset()         { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()    {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94ac02770f363096, []int{1}
}

func (m *DiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryResponse.Unmarshal(m, b)
}
func (m *DiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *DiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryResponse.Merge(m, src)
}
func (m *DiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoveryResponse.Size(m)
}
func (m *DiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryResponse proto.InternalMessageInfo

func (m *DiscoveryResponse) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *DiscoveryResponse) GetResources() []*any.Any {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *DiscoveryResponse) GetCanary() bool {
	if m != nil {
		return m.Canary
	}
	return false
}

func (m *DiscoveryResponse) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *DiscoveryResponse) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *DiscoveryResponse) GetControlPlane() *core.ControlPlane {
	if m != nil {
		return m.ControlPlane
	}
	return nil
}

type DeltaDiscoveryRequest struct {
	Node                     *core.Node        `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	TypeUrl                  string            `protobuf:"bytes,2,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	ResourceNamesSubscribe   []string          `protobuf:"bytes,3,rep,name=resource_names_subscribe,json=resourceNamesSubscribe,proto3" json:"resource_names_subscribe,omitempty"`
	ResourceNamesUnsubscribe []string          `protobuf:"bytes,4,rep,name=resource_names_unsubscribe,json=resourceNamesUnsubscribe,proto3" json:"resource_names_unsubscribe,omitempty"`
	InitialResourceVersions  map[string]string `protobuf:"bytes,5,rep,name=initial_resource_versions,json=initialResourceVersions,proto3" json:"initial_resource_versions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ResponseNonce            string            `protobuf:"bytes,6,opt,name=response_nonce,json=responseNonce,proto3" json:"response_nonce,omitempty"`
	ErrorDetail              *status.Status    `protobuf:"bytes,7,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}          `json:"-"`
	XXX_unrecognized         []byte            `json:"-"`
	XXX_sizecache            int32             `json:"-"`
}

func (m *DeltaDiscoveryRequest) Reset()         { *m = DeltaDiscoveryRequest{} }
func (m *DeltaDiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*DeltaDiscoveryRequest) ProtoMessage()    {}
func (*DeltaDiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94ac02770f363096, []int{2}
}

func (m *DeltaDiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeltaDiscoveryRequest.Unmarshal(m, b)
}
func (m *DeltaDiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeltaDiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *DeltaDiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeltaDiscoveryRequest.Merge(m, src)
}
func (m *DeltaDiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_DeltaDiscoveryRequest.Size(m)
}
func (m *DeltaDiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeltaDiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeltaDiscoveryRequest proto.InternalMessageInfo

func (m *DeltaDiscoveryRequest) GetNode() *core.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *DeltaDiscoveryRequest) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *DeltaDiscoveryRequest) GetResourceNamesSubscribe() []string {
	if m != nil {
		return m.ResourceNamesSubscribe
	}
	return nil
}

func (m *DeltaDiscoveryRequest) GetResourceNamesUnsubscribe() []string {
	if m != nil {
		return m.ResourceNamesUnsubscribe
	}
	return nil
}

func (m *DeltaDiscoveryRequest) GetInitialResourceVersions() map[string]string {
	if m != nil {
		return m.InitialResourceVersions
	}
	return nil
}

func (m *DeltaDiscoveryRequest) GetResponseNonce() string {
	if m != nil {
		return m.ResponseNonce
	}
	return ""
}

func (m *DeltaDiscoveryRequest) GetErrorDetail() *status.Status {
	if m != nil {
		return m.ErrorDetail
	}
	return nil
}

type DeltaDiscoveryResponse struct {
	SystemVersionInfo    string      `protobuf:"bytes,1,opt,name=system_version_info,json=systemVersionInfo,proto3" json:"system_version_info,omitempty"`
	Resources            []*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	TypeUrl              string      `protobuf:"bytes,4,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	RemovedResources     []string    `protobuf:"bytes,6,rep,name=removed_resources,json=removedResources,proto3" json:"removed_resources,omitempty"`
	Nonce                string      `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeltaDiscoveryResponse) Reset()         { *m = DeltaDiscoveryResponse{} }
func (m *DeltaDiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*DeltaDiscoveryResponse) ProtoMessage()    {}
func (*DeltaDiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94ac02770f363096, []int{3}
}

func (m *DeltaDiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeltaDiscoveryResponse.Unmarshal(m, b)
}
func (m *DeltaDiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeltaDiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *DeltaDiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeltaDiscoveryResponse.Merge(m, src)
}
func (m *DeltaDiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_DeltaDiscoveryResponse.Size(m)
}
func (m *DeltaDiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeltaDiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeltaDiscoveryResponse proto.InternalMessageInfo

func (m *DeltaDiscoveryResponse) GetSystemVersionInfo() string {
	if m != nil {
		return m.SystemVersionInfo
	}
	return ""
}

func (m *DeltaDiscoveryResponse) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *DeltaDiscoveryResponse) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *DeltaDiscoveryResponse) GetRemovedResources() []string {
	if m != nil {
		return m.RemovedResources
	}
	return nil
}

func (m *DeltaDiscoveryResponse) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type Resource struct {
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Aliases              []string `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Resource             *any.Any `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_94ac02770f363096, []int{4}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *Resource) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Resource) GetResource() *any.Any {
	if m != nil {
		return m.Resource
	}
	return nil
}

func init() {
	proto.RegisterType((*DiscoveryRequest)(nil), "envoy.api.v3alpha.DiscoveryRequest")
	proto.RegisterType((*DiscoveryResponse)(nil), "envoy.api.v3alpha.DiscoveryResponse")
	proto.RegisterType((*DeltaDiscoveryRequest)(nil), "envoy.api.v3alpha.DeltaDiscoveryRequest")
	proto.RegisterMapType((map[string]string)(nil), "envoy.api.v3alpha.DeltaDiscoveryRequest.InitialResourceVersionsEntry")
	proto.RegisterType((*DeltaDiscoveryResponse)(nil), "envoy.api.v3alpha.DeltaDiscoveryResponse")
	proto.RegisterType((*Resource)(nil), "envoy.api.v3alpha.Resource")
}

func init() { proto.RegisterFile("envoy/api/v3alpha/discovery.proto", fileDescriptor_94ac02770f363096) }

var fileDescriptor_94ac02770f363096 = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6b, 0xdb, 0x4a,
	0x10, 0x45, 0xb6, 0xe3, 0xd8, 0xe3, 0x24, 0xc4, 0x7b, 0x73, 0x13, 0xc5, 0x37, 0x70, 0x1d, 0xd3,
	0x82, 0xa1, 0x20, 0x85, 0x84, 0x42, 0x5a, 0xfa, 0xd2, 0x34, 0x79, 0x48, 0x1f, 0x42, 0x50, 0x48,
	0x5e, 0xc5, 0x5a, 0x9e, 0xa4, 0x4b, 0x95, 0x5d, 0x75, 0x57, 0x32, 0xd5, 0x63, 0xa1, 0x50, 0xe8,
	0xbf, 0xec, 0x1f, 0x29, 0x45, 0xab, 0x5d, 0x7f, 0xc4, 0x6a, 0xf0, 0x9b, 0x66, 0xe6, 0xcc, 0xd9,
	0xf9, 0x38, 0x23, 0x38, 0x44, 0x3e, 0x11, 0xb9, 0x4f, 0x13, 0xe6, 0x4f, 0x4e, 0x68, 0x9c, 0x7c,
	0xa2, 0xfe, 0x98, 0xa9, 0x48, 0x4c, 0x50, 0xe6, 0x5e, 0x22, 0x45, 0x2a, 0x48, 0x57, 0x43, 0x3c,
	0x9a, 0x30, 0xcf, 0x40, 0x7a, 0x15, 0x59, 0x91, 0x90, 0xe8, 0x8f, 0xa8, 0xc2, 0x32, 0xab, 0xb7,
	0xff, 0x20, 0xc4, 0x43, 0x8c, 0xbe, 0xb6, 0x46, 0xd9, 0xbd, 0x4f, 0xb9, 0x21, 0xec, 0xed, 0x99,
	0x90, 0x4c, 0x22, 0x5f, 0xa5, 0x34, 0xcd, 0x54, 0x19, 0x18, 0xfc, 0xa8, 0xc1, 0xf6, 0xb9, 0x7d,
	0x3d, 0xc0, 0x2f, 0x19, 0xaa, 0x94, 0x1c, 0xc2, 0xc6, 0x04, 0xa5, 0x62, 0x82, 0x87, 0x8c, 0xdf,
	0x0b, 0xd7, 0xe9, 0x3b, 0xc3, 0x76, 0xd0, 0x31, 0xbe, 0x4b, 0x7e, 0x2f, 0xc8, 0x11, 0x34, 0xb8,
	0x18, 0xa3, 0x5b, 0xeb, 0x3b, 0xc3, 0xce, 0xf1, 0x81, 0xb7, 0x54, 0xb0, 0x57, 0x54, 0xe7, 0x5d,
	0x89, 0x31, 0x06, 0x1a, 0x49, 0x5e, 0xc2, 0x96, 0x44, 0x25, 0x32, 0x19, 0x61, 0xc8, 0xe9, 0x23,
	0x2a, 0xb7, 0xde, 0xaf, 0x0f, 0xdb, 0xc1, 0xa6, 0xf5, 0x5e, 0x15, 0x4e, 0xb2, 0x0f, 0xad, 0x34,
	0x4f, 0x30, 0xcc, 0x64, 0xec, 0x36, 0xf4, 0xbb, 0xeb, 0x85, 0x7d, 0x2b, 0x63, 0xc3, 0x90, 0x08,
	0xae, 0x30, 0xe4, 0x82, 0x47, 0xe8, 0xae, 0x69, 0xc0, 0xa6, 0xf5, 0x5e, 0x15, 0x4e, 0xf2, 0x1a,
	0x36, 0x50, 0x4a, 0x21, 0xc3, 0x31, 0xa6, 0x94, 0xc5, 0x6e, 0x53, 0x97, 0x48, 0xbc, 0x72, 0x04,
	0x9e, 0x4c, 0x22, 0xef, 0x46, 0x8f, 0x20, 0xe8, 0x68, 0xdc, 0xb9, 0x86, 0x0d, 0x7e, 0x3b, 0xd0,
	0x9d, 0x9b, 0x44, 0xc9, 0xb8, 0xca, 0x28, 0x8e, 0xa1, 0x6d, 0x5b, 0x50, 0x6e, 0xad, 0x5f, 0x1f,
	0x76, 0x8e, 0x77, 0xec, 0x63, 0x76, 0x15, 0xde, 0x7b, 0x9e, 0x07, 0x33, 0x18, 0xd9, 0x85, 0x66,
	0x44, 0x39, 0x95, 0xb9, 0x5b, 0xef, 0x3b, 0xc3, 0x56, 0x60, 0xac, 0xe7, 0xba, 0xdf, 0x81, 0xb5,
	0xf9, 0xa6, 0x4b, 0x83, 0x5c, 0xc2, 0x66, 0x24, 0x78, 0x2a, 0x45, 0x1c, 0x26, 0x31, 0xe5, 0x68,
	0xba, 0x7d, 0xf1, 0xb7, 0x85, 0x7c, 0x28, 0xc1, 0xd7, 0x05, 0x36, 0xd8, 0x88, 0xe6, 0xac, 0xc1,
	0xcf, 0x06, 0xfc, 0x7b, 0x8e, 0x71, 0x4a, 0x97, 0xf4, 0x60, 0x97, 0xed, 0xac, 0xbc, 0xec, 0xf9,
	0x3e, 0x6a, 0x8b, 0x7d, 0x9c, 0x82, 0xbb, 0xa8, 0x83, 0x50, 0x65, 0x23, 0x15, 0x49, 0x36, 0x42,
	0xa3, 0x88, 0xdd, 0x05, 0x45, 0xdc, 0xd8, 0x28, 0x79, 0x07, 0xbd, 0x27, 0x99, 0x19, 0x9f, 0xe5,
	0x36, 0x74, 0xae, 0xbb, 0x90, 0x7b, 0x3b, 0x8b, 0x93, 0x6f, 0x0e, 0xec, 0x33, 0xce, 0x52, 0x46,
	0xe3, 0x70, 0x4a, 0x63, 0xf6, 0xa8, 0xdc, 0x35, 0xbd, 0xb7, 0x8b, 0x8a, 0xd6, 0x2a, 0x47, 0xe2,
	0x5d, 0x96, 0x4c, 0x81, 0x21, 0xba, 0x33, 0x3c, 0x17, 0x3c, 0x95, 0x79, 0xb0, 0xc7, 0xaa, 0xa3,
	0x15, 0x0a, 0x6e, 0xae, 0xa2, 0xe0, 0xf5, 0x95, 0x14, 0xdc, 0xfb, 0x08, 0x07, 0xcf, 0x95, 0x45,
	0xb6, 0xa1, 0xfe, 0x19, 0x73, 0x23, 0xe1, 0xe2, 0xb3, 0xd0, 0xd4, 0x84, 0xc6, 0x19, 0x9a, 0x1d,
	0x95, 0xc6, 0xdb, 0xda, 0xa9, 0x33, 0xf8, 0xe5, 0xc0, 0xee, 0xd3, 0xce, 0xcd, 0x49, 0x78, 0xf0,
	0x8f, 0xca, 0x55, 0x8a, 0x8f, 0x61, 0xc5, 0x65, 0x74, 0xcb, 0xd0, 0xdd, 0xdc, 0x7d, 0xbc, 0x59,
	0xbe, 0x8f, 0xff, 0x2a, 0xe6, 0x6c, 0x6b, 0x9e, 0x3f, 0x93, 0x67, 0xce, 0xe1, 0x15, 0x74, 0x25,
	0x3e, 0x8a, 0x09, 0x8e, 0xc3, 0x19, 0x7b, 0x53, 0x6b, 0x60, 0xdb, 0x04, 0x82, 0x29, 0x4f, 0xe5,
	0xed, 0x0c, 0xbe, 0x3b, 0xd0, 0xb2, 0x18, 0x42, 0xa0, 0x51, 0x68, 0x4a, 0xdf, 0x63, 0x3b, 0xd0,
	0xdf, 0xc4, 0x85, 0x75, 0x1a, 0x33, 0xaa, 0x50, 0x19, 0x75, 0x59, 0xb3, 0x88, 0x98, 0xe6, 0x4d,
	0xdf, 0xd6, 0x24, 0x47, 0xd0, 0xb2, 0xf5, 0x98, 0x9f, 0x63, 0xf5, 0xcf, 0x60, 0x8a, 0x3a, 0x3b,
	0x81, 0xff, 0x99, 0x28, 0x07, 0x92, 0x48, 0xf1, 0x35, 0x5f, 0x9e, 0xcd, 0xd9, 0xd6, 0x74, 0x0b,
	0xd7, 0x05, 0xc7, 0xb5, 0x33, 0x6a, 0x6a, 0xb2, 0x93, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0f,
	0x47, 0x42, 0xb8, 0x4d, 0x06, 0x00, 0x00,
}
