receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4319"

processors:
  batch:

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
