name: Dependency Changes

# Trigger on PRs.
on:
  pull_request:

permissions:
  contents: read

jobs:
  # Compare dependencies before and after this PR.
  dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: "**/*go.sum"

      # Run the commands to generate dependencies before and after and compare.
      - name: Compare dependencies
        run: |
          set -eu
          TEMP_DIR="$(mktemp -d)"
          # GITHUB_BASE_REF is set when the job is triggered by a PR.
          TARGET_REF="${GITHUB_BASE_REF:-master}"

          mkdir "${TEMP_DIR}/after"
          scripts/gen-deps.sh "${TEMP_DIR}/after"

          git checkout "origin/${TARGET_REF}"
          mkdir "${TEMP_DIR}/before"
          scripts/gen-deps.sh "${TEMP_DIR}/before"

          echo "Comparing dependencies..."
          cd "${TEMP_DIR}"
          # Run grep in a sub-shell since bash does not support ! in the middle of a pipe
          diff -u0 -r "before" "after" | bash -c '! grep -v "@@"'
          echo "No changes detected."
