name: Dependency Changes

# Trigger on PRs.
on:
  pull_request:

permissions:
  contents: read

jobs:
  # Compare dependencies before and after this PR.
  dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: "**/*go.sum"

      # Run the commands to generate dependencies before and after and compare.
      - name: Compare dependencies
        run: |
          set -eux
          TEMP_DIR="$(mktemp -d)"
          # GITHUB_BASE_REF is set when the job is triggered by a PR.
          TARGET_REF="${GITHUB_BASE_REF:-master}"
          # GITHUB_HEAD_REF is set when the job is triggered by a PR.
          SOURCE_REF="${GITHUB_HEAD_REF:-source}"

          # Replace special characters in the branch names.
          BEFORE_DIR_NAME="$(echo "${SOURCE_REF}" | sed 's/[^a-zA-Z0-9._-]/_/g')"
          AFTER_DIR_NAME="$(echo "${TARGET_REF}" | sed 's/[^a-zA-Z0-9._-]/_/g')"


          mkdir "${TEMP_DIR}/${AFTER_DIR_NAME}"
          scripts/gen-deps.sh "${TEMP_DIR}/${AFTER_DIR_NAME}"

          git checkout "origin/${TARGET_REF}"
          mkdir "${TEMP_DIR}/${BEFORE_DIR_NAME}"
          scripts/gen-deps.sh "${TEMP_DIR}/${BEFORE_DIR_NAME}"

          echo "Comparing dependencies..."
          cd "${TEMP_DIR}"
          # Run grep in a sub-shell since bash does not support ! in the middle of a pipe
          diff -u0 -r "./${BEFORE_DIR_NAME}" "./${AFTER_DIR_NAME}" | bash -c '! grep -v "@@"'
          echo "No changes detected."
