# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    paths_ignore:
    - 'Documentation/**'
    - 'version.go'

env:
  VET_SKIP_PROTO: 1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2

      # Runs a single command using the runners shell
      - name: Install vet
        run: |
          ./vet.sh -install
          which go
          which golint

      # Runs a set of commands using the runners shell
      - name: Run vet
        run: ./vet.sh

      - name: Run tests
        run: make test
